name: "Tests: Integration"

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  checks: write
  contents: read
  pull-requests: read

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --include=dev
        
      - name: Install system dependencies and direnv
        run: sudo apt-get install tree xvfb direnv

      - name: Setup direnv
        run: |
          echo 'eval "$(direnv hook bash)"' >> ~/.bashrc
          source ~/.bashrc
          direnv allow .

  run-tests:
    needs: setup-environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      

      - name: Run tests
        run: |
          # Ensure PATH includes node_modules/.bin
          export PATH="$PWD/node_modules/.bin:$PATH"
          xvfb-run -a ./src/test/run-with-verbosity.js

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/