name: "Tests: Integration"

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  checks: write
  contents: read
  pull-requests: read

jobs:
  test:
    uses: ./.github/workflows/base-setup.yml

  run-tests:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
        
      - name: install tree
        run: sudo apt-get install tree xvfb

      - name: Run tests
        run: ls node_modules && ls node_modules/.bin/  &&  xvfb-run -a  ./src/test/run-with-verbosity.js

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/